replacements:
  textToReplace:
    replacement: "Text To Replace With"
    hover: true
    hoverText: "this will show when you hover over it"

  textToReplace2:
    replacement: "Text To Replace With"
    hover: true
    hoverText: "this will show when you hover over it"

  textToReplace3:
    replacement: "Text To Replace With"
    hover: true
    hoverText: "this will show when you hover over it"